# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_coin_coin_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical',
            name='votes',
        ),
    ]
