# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_coin_coin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='coin_image',
        ),
    ]
