# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_coin_coin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/', verbose_name='img'),
            preserve_default=False,
        ),
    ]
