# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_coin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gussed_name', models.CharField(max_length=1024)),
                ('account_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='polls.Account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='polls.Account')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='token_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Coin'),
        ),
    ]
