# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170909_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
