# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170910_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='updated_at',
        ),
    ]
