# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170910_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='largested_timestamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TimeStamp'),
        ),
    ]
