# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_account_account_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_memo',
        ),
    ]
